version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run: |
          docker build -t bbensky/delicate-flowers:$CIRCLE_SHA1 .
          docker login -u $QUAY_USER -p $QUAY_TOKEN quay.io
          docker push bbensky/delicate-flowers:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
